Fixing "Elixir.isWatching is not a function" bug
Bug: running "gulp" or "gulp watch" caused a TypeError, and crashed.
Fix: Removing method call on line 162, referencing "isWatching" as a property instead.